# fly.toml file generated for parknow on 2023-07-16T20:55:47+08:00

app = "parknow"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[env]
  PORT = "3001"

[[services]]
  internal_port = 3001
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[processes]
  app = "node index.js"
